# Worker config
CONFIG_WORKER_MODE_EMAIL = 'email'
CONFIG_WORKER_MODE_SMS = 'SMS'
CONFIG_EMAIL_OTP_TEMPLATE_NAME = 'email_otp_template.j2'
CONFIG_SMS_OTP_TEMPLATE_NAME = 'sms_otp_template.j2'

# Message fields
MESSAGE_FIELD_ONETIME_PASS = 'onetime_pass'
MESSAGE_FIELD_CONTENT = 'the_content'
MESSAGE_FIELD_EMAIL = 'recipient'
MESSAGE_FIELD_SUBJECT = 'subject'
MESSAGE_FIELD_MOBILE = 'recipient'
MESSAGE_FIELD_GUID = 'guid'

MESSAGE_TEMPLATE = 'templateFile'

# Message Mimetext fields
MIMETEXT_FIELD_SUBJECT = 'Subject'
MIMETEXT_FIELD_RECIPIENT_TO = 'To'
MIMETEXT_FIELD_SENDER_FROM = 'From'

MOBILE_NUMBER_COUNTRY_CODE = '+44'
